import React, { useEffect, useState } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import { toast } from "sonner";
import { cn } from "@/lib/utils";

const PreparingPrescription = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const { vetName, petName, selectedPet, appointmentId } = location.state || {};

  const finalVetName = vetName || "Dr. Vikram Malhotra";
  const finalPetName = petName || "Luna";
  const finalBreed = selectedPet ? `Dog • ${selectedPet}` : "Dog • Golden Retriever";
  const finalApptId = appointmentId ? `ID: #${appointmentId}` : "ID: #SRV-9921";

  const [isAlertSet, setIsAlertSet] = useState(false);

  // Dynamically inject stylesheets for Inter, Material Symbols, and Phosphor Icons
  useEffect(() => {
    const linkInter = document.createElement("link");
    linkInter.href = "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap";
    linkInter.rel = "stylesheet";
    document.head.appendChild(linkInter);

    const linkSymbols = document.createElement("link");
    linkSymbols.href = "https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0";
    linkSymbols.rel = "stylesheet";
    document.head.appendChild(linkSymbols);

    const linkPhosphor = document.createElement("link");
    linkPhosphor.href = "https://unpkg.com/@phosphor-icons/web@2.1.1/src/style.css";
    linkPhosphor.rel = "stylesheet";
    document.head.appendChild(linkPhosphor);

    // Auto navigate after 8 seconds to digital prescription, simulating vet completing it
    const timer = setTimeout(() => {
      toast.success("Prescription generated by Dr. Vikram! Loading prescription...");
      navigate("/buyer/vet/prescription", { state: location.state });
    }, 8000);

    return () => {
      document.head.removeChild(linkInter);
      document.head.removeChild(linkSymbols);
      document.head.removeChild(linkPhosphor);
      clearTimeout(timer);
    };
  }, [navigate, location.state]);

  const handleNotifyMe = () => {
    setIsAlertSet(true);
    toast.success("Notification Alert Set! We'll ping you as soon as the prescription is ready.");
    
    setTimeout(() => {
      setIsAlertSet(false);
    }, 4000);
  };

  return (
    <div className="preparing-prescription-root">
      {/* Scoped CSS Styles injected directly here */}
      <style>{`
        .preparing-prescription-root {
          --primary-gradient: linear-gradient(135deg, #DE54A4 0%, #8A4BFA 100%);
          --text-dark: #1E1E24;
          --text-muted: #6B7280;
          --bg-color: #FAFAFC;
          --card-bg: #FFFFFF;
          
          --primary: #DE468B; 
          --primary-light: #FCE7F3; 
          --white: #FFFFFF;
          --text-gray: #6B7280;
          --text-light-gray: #9CA3AF;
          --border-color: #EFEFF5;
          --success-green: #10B981;
          --card-shadow: 0 4px 20px rgba(0,0,0,0.02);
          --border-radius: 24px;

          background-color: #E5E7EB; 
          display: flex;
          justify-content: center;
          align-items: center;
          min-height: 100vh;
          font-family: 'Inter', sans-serif;
        }

        .preparing-prescription-root * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
          -webkit-tap-highlight-color: transparent;
        }

        /* Mobile App Container */
        .preparing-prescription-root .app-container {
          width: 100%;
          max-width: 400px;
          height: 100vh;
          max-height: 850px;
          background-color: var(--bg-color);
          position: relative;
          overflow: hidden;
          display: flex;
          flex-direction: column;
          box-shadow: 0 24px 48px rgba(0, 0, 0, 0.1);
          border-radius: 24px;
        }

        @media (max-width: 480px) {
          .preparing-prescription-root .app-container {
            max-height: 100vh;
            border-radius: 0px;
          }
          .preparing-prescription-root {
            background-color: var(--bg-color);
          }
        }

        /* Header */
        .preparing-prescription-root .header {
          display: flex;
          align-items: center;
          padding: 24px 20px;
          position: relative;
        }

        .preparing-prescription-root .back-btn {
          width: 40px;
          height: 40px;
          border-radius: 50%;
          border: 1px solid #E5E7EB;
          background: var(--card-bg);
          display: flex;
          justify-content: center;
          align-items: center;
          cursor: pointer;
          transition: background 0.2s;
          outline: none;
        }

        .preparing-prescription-root .back-btn:active {
          background: #F3F4F6;
        }

        .preparing-prescription-root .header-title {
          flex-grow: 1;
          text-align: center;
          font-size: 16px;
          font-weight: 600;
          color: var(--text-dark);
          margin-right: 40px;
        }

        /* Main Content */
        .preparing-prescription-root .content {
          flex-grow: 1;
          padding: 20px;
          display: flex;
          flex-direction: column;
          align-items: center;
          text-align: center;
          overflow-y: auto;
        }

        /* Animated Hero Icon */
        .preparing-prescription-root .hero-icon-container {
          position: relative;
          margin: 30px 0;
          animation: float 4s ease-in-out infinite;
        }

        .preparing-prescription-root .main-icon {
          width: 120px;
          height: 120px;
          background: var(--primary-gradient);
          border-radius: 32px;
          display: flex;
          justify-content: center;
          align-items: center;
          color: white;
          font-size: 56px;
          box-shadow: 0 16px 32px rgba(138, 75, 250, 0.2);
        }

        .preparing-prescription-root .sync-badge {
          position: absolute;
          bottom: -10px;
          right: -10px;
          width: 48px;
          height: 48px;
          background: var(--card-bg);
          border-radius: 50%;
          display: flex;
          justify-content: center;
          align-items: center;
          box-shadow: 0 8px 16px rgba(0, 0, 0, 0.1);
          color: #8A4BFA;
          font-size: 24px;
        }

        .preparing-prescription-root .sync-icon {
          animation: spin 2s linear infinite;
        }

        /* Typography */
        .preparing-prescription-root .title-group {
          margin-bottom: 16px;
        }

        .preparing-prescription-root .title-light {
          font-size: 24px;
          font-weight: 600;
          color: var(--text-dark);
          margin-bottom: 4px;
        }

        .preparing-prescription-root .title-gradient {
          font-size: 24px;
          font-weight: 700;
          background: var(--primary-gradient);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
        }

        .preparing-prescription-root .subtitle {
          font-size: 14px;
          color: var(--text-muted);
          line-height: 1.5;
          margin-bottom: 10px;
          padding: 0 10px;
        }

        /* NEW CARDS STYLING */
        .preparing-prescription-root .cards-wrapper {
          width: 100%;
          display: flex;
          flex-direction: column;
          gap: 16px;
          margin-top: 16px;
        }

        .preparing-prescription-root .doctor-card {
          background: var(--white);
          border-radius: var(--border-radius);
          padding: 16px;
          display: flex;
          align-items: center;
          gap: 16px;
          box-shadow: var(--card-shadow);
          border: 1px solid var(--border-color);
          text-align: left;
        }

        .preparing-prescription-root .doctor-avatar {
          width: 60px;
          height: 60px;
          border-radius: 50%;
          object-fit: cover;
          border: 2px solid var(--primary-light);
        }

        .preparing-prescription-root .doctor-info h2 {
          font-size: 16px;
          font-weight: 700;
          margin-bottom: 4px;
          color: var(--text-dark);
        }

        .preparing-prescription-root .doctor-info p {
          color: var(--text-gray);
          font-size: 12px;
          font-weight: 500;
          margin-bottom: 2px;
        }

        .preparing-prescription-root .doctor-info .reg-id {
          color: var(--text-light-gray);
          font-size: 11px;
          display: flex;
          align-items: center;
          gap: 4px;
        }

        .preparing-prescription-root .patient-card {
          background: var(--white);
          border-radius: var(--border-radius);
          padding: 16px;
          display: flex;
          align-items: center;
          gap: 14px;
          box-shadow: var(--card-shadow);
          border: 1px solid var(--border-color);
          text-align: left;
        }

        .preparing-prescription-root .avatar-container {
          position: relative;
          flex-shrink: 0;
        }

        .preparing-prescription-root .avatar {
          width: 74px;
          height: 74px;
          border-radius: 50%;
          object-fit: cover;
          border: 2px solid var(--primary);
          padding: 2px;
        }

        .preparing-prescription-root .status-dot {
          position: absolute;
          bottom: 2px;
          right: 2px;
          width: 14px;
          height: 14px;
          background-color: var(--success-green);
          border: 2.5px solid var(--white);
          border-radius: 50%;
        }

        .preparing-prescription-root .patient-info {
          flex: 1;
          min-width: 0; 
        }

        .preparing-prescription-root .patient-info h2 {
          color: var(--text-dark);
          font-size: 17px;
          font-weight: 700;
          margin-bottom: 2px;
          white-space: nowrap;
          overflow: hidden;
          text-overflow: ellipsis;
        }

        .preparing-prescription-root .pet-breed {
          color: var(--primary);
          font-size: 12px;
          font-weight: 600;
          margin-bottom: 4px;
        }

        .preparing-prescription-root .patient-info p {
          color: var(--text-gray);
          font-size: 12px;
          margin-bottom: 2px;
          font-weight: 500;
        }
        
        .preparing-prescription-root .tags {
          display: flex;
          gap: 6px;
          margin-top: 8px;
          flex-wrap: nowrap; 
          overflow-x: auto;
          -ms-overflow-style: none;
          scrollbar-width: none;
        }
        
        .preparing-prescription-root .tags::-webkit-scrollbar { display: none; }

        .preparing-prescription-root .tag {
          padding: 6px 10px;
          border-radius: 12px;
          font-size: 9px;
          font-weight: 700;
          letter-spacing: 0.5px;
          white-space: nowrap;
        }

        .preparing-prescription-root .tag-primary {
          background-color: var(--primary-light);
          color: var(--primary);
        }

        .preparing-prescription-root .tag-secondary {
          background-color: #F0F0F5;
          color: var(--text-gray);
        }

        /* Bottom Fixed Button */
        .preparing-prescription-root .footer {
          padding: 20px;
          background: linear-gradient(to top, var(--bg-color) 80%, transparent);
        }

        .preparing-prescription-root .action-btn {
          width: 100%;
          padding: 18px;
          border: none;
          border-radius: 16px;
          color: white;
          font-size: 16px;
          font-weight: 600;
          cursor: pointer;
          transition: transform 0.2s, box-shadow 0.2s, background-color 0.3s;
          outline: none;
        }

        .preparing-prescription-root .action-btn:active {
          transform: scale(0.98);
        }

        /* Animations */
        @keyframes spin {
          100% { transform: rotate(360deg); }
        }

        @keyframes float {
          0%, 100% { transform: translateY(0); }
          50% { transform: translateY(-10px); }
        }
      `}</style>

      <div className="app-container">
        <div className="header">
          <button className="back-btn" onClick={() => navigate(-1)} aria-label="Go back">
            <i className="ph ph-arrow-left"></i>
          </button>
          <div className="header-title">Digital Prescription</div>
        </div>

        <div className="content">
          <div className="hero-icon-container">
            <div className="main-icon">
              <i className="ph-fill ph-file-text"></i>
            </div>
            <div className="sync-badge">
              <i className="ph ph-arrows-clockwise sync-icon"></i>
            </div>
          </div>

          <div className="title-group">
            <div className="title-light">Preparing Your</div>
            <div className="title-gradient">Digital Prescription</div>
          </div>

          <p className="subtitle">
            Your vet is finalizing the prescription. Feel free to stay here or leave — we'll notify you as soon as it's ready.
          </p>

          <div className="cards-wrapper">
            <div className="doctor-card">
              <img 
                src="https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=150&q=80" 
                alt="Dr. Vikram Malhotra" 
                className="doctor-avatar" 
              />
              <div className="doctor-info">
                <h2>{finalVetName}</h2>
                <p>Senior Veterinarian</p>
                <div className="reg-id">
                  <span className="material-symbols-outlined" style={{ fontSize: "14px" }}>verified</span>
                  REG ID: VET-88291
                </div>
              </div>
            </div>

            <div className="patient-card">
              <div className="avatar-container">
                <img 
                  src="https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=150&q=80" 
                  alt="Luna" 
                  className="avatar" 
                />
                <div className="status-dot"></div>
              </div>
              <div className="patient-info">
                <h2>Prescription for {finalPetName}</h2>
                <div className="pet-breed">{finalBreed}</div>
                <p>3 Years Old • {finalApptId}</p>
                <div className="tags">
                  <span className="tag tag-primary">CONSULTATION: VIDEO CALL</span>
                  <span className="tag tag-secondary">WEIGHT: 24KG</span>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="footer">
          <button 
            type="button"
            className="action-btn" 
            onClick={handleNotifyMe}
            style={{
              background: isAlertSet ? "#10B981" : "var(--primary-gradient)",
              boxShadow: isAlertSet ? "0 8px 24px rgba(16, 185, 129, 0.25)" : "0 8px 24px rgba(138, 75, 250, 0.25)",
            }}
          >
            {isAlertSet ? (
              <>
                <i className="ph ph-check-circle" style={{ marginRight: "8px", verticalAlign: "middle", fontSize: "20px" }}></i> Alert Set
              </>
            ) : (
              "Notify Me When Ready"
            )}
          </button>
        </div>
      </div>
    </div>
  );
};

export default PreparingPrescription;
