// Comprehensive data of Indian States, Union Territories and their cities as of 2026.
// This ensures reliable location entries without spelling errors/accidental spaces.

export interface StateData {
  name: string;
  cities: string[];
}

export const INDIA_STATES_AND_CITIES: Record<string, string[]> = {
  "Andhra Pradesh": [
    "Visakhapatnam",
    "Vijayawada",
    "Guntur",
    "Nellore",
    "Kurnool",
    "Rajahmundry (Rajamahendravaram)",
    "Tirupati",
    "Kakinada",
    "Kadapa",
    "Anantapur",
    "Eluru",
    "Vizianagaram",
    "Ongole",
    "Nandyal",
    "Machilipatnam",
    "Adoni",
    "Tenali",
    "Proddatur",
    "Chittoor",
    "Hindupur",
    "Bhimavaram",
    "Madanapalle"
  ],
  "Arunachal Pradesh": [
    "Itanagar",
    "Naharlagun",
    "Pasighat",
    "Tawang",
    "Ziro",
    "Tezu",
    "Bomdila",
    "Aalo"
  ],
  "Assam": [
    "Guwahati",
    "Silchar",
    "Dibrugarh",
    "Jorhat",
    "Nagaon",
    "Tinsukia",
    "Tezpur",
    "Bongaigaon",
    "Dhubri",
    "Karimganj",
    "Sibsagar",
    "Goalpara",
    "North Lakhimpur",
    "Diphu"
  ],
  "Bihar": [
    "Patna",
    "Gaya",
    "Bhagalpur",
    "Muzaffarpur",
    "Purnia",
    "Darbhanga",
    "Bihar Sharif",
    "Arrah (Ara)",
    "Begusarai",
    "Katihar",
    "Munger",
    "Chhapra",
    "Danapur",
    "Saharsa",
    "Hajipur",
    "Sasaram",
    "Bettiah",
    "Motihari",
    "Siwan",
    "Kishanganj"
  ],
  "Chhattisgarh": [
    "Raipur",
    "Bhilai",
    "Bilaspur",
    "Korba",
    "Rajnandgaon",
    "Jagdalpur",
    "Ambikapur",
    "Dhamtari",
    "Durg",
    "Raigarh",
    "Champa",
    "Mahasamund"
  ],
  "Goa": [
    "Panaji",
    "Margao",
    "Vasco da Gama",
    "Mapusa",
    "Ponda",
    "Bicholim",
    "Curchorem"
  ],
  "Gujarat": [
    "Ahmedabad",
    "Surat",
    "Vadodara (Baroda)",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
    "Gandhinagar",
    "Anand",
    "Nadiad",
    "Morbi",
    "Mehsana",
    "Surendranagar",
    "Bharuch",
    "Valsad",
    "Vapi",
    "Navsari",
    "Veraval",
    "Godhra",
    "Patan",
    "Porbandar"
  ],
  "Haryana": [
    "Gurugram",
    "Faridabad",
    "Sonipat",
    "Panipat",
    "Ambala",
    "Yamunanagar",
    "Rohtak",
    "Hisar",
    "Karnal",
    "Panchkula",
    "Kurukshetra",
    "Sirsa",
    "Bahadurgarh",
    "Jind",
    "Thanesar",
    "Kaithal",
    "Rewari",
    "Palwal",
    "Hansi",
    "Narnaul",
    "Fatehabad",
    "Tohana"
  ],
  "Himachal Pradesh": [
    "Shimla",
    "Dharamshala",
    "Solan",
    "Mandi",
    "Bilaspur",
    "Kullu",
    "Hamirpur",
    "Una",
    "Nahan",
    "Chamba",
    "Kangra",
    "Baddi",
    "Sundernagar"
  ],
  "Jharkhand": [
    "Ranchi",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro Steel City",
    "Deoghar",
    "Phusro",
    "Hazaribagh",
    "Giridih",
    "Ramgarh",
    "Medininagar (Daltonganj)",
    "Chas",
    "Sahibganj",
    "Chaibasa"
  ],
  "Karnataka": [
    "Bengaluru (Bangalore)",
    "Mysuru (Mysore)",
    "Hubballi-Dharwad",
    "Mangaluru (Mangalore)",
    "Belagavi (Belgaum)",
    "Kalaburagi (Gulbarga)",
    "Davanagere",
    "Ballari (Bellary)",
    "Vijayapura (Bijapur)",
    "Shivamogga (Shimoga)",
    "Tumakuru (Tumkur)",
    "Udupi",
    "Bidar",
    "Hosapete",
    "Hassan",
    "Chikkamagaluru",
    "Chitradurga",
    "Ranebennur",
    "Mandya",
    "Dharwad"
  ],
  "Kerala": [
    "Thiruvananthapuram (Trivandrum)",
    "Kochi (Cochin)",
    "Kozhikode (Calicut)",
    "Kollam",
    "Thrissur",
    "Alappuzha",
    "Palakkad",
    "Kottayam",
    "Manjeri",
    "Thalassery",
    "Ponnani",
    "Kanhangad",
    "Vatakara",
    "Kannur",
    "Malappuram"
  ],
  "Madhya Pradesh": [
    "Indore",
    "Bhopal",
    "Jabalpur",
    "Gwalior",
    "Ujjain",
    "Sagar",
    "Dewas",
    "Satna",
    "Ratlam",
    "Rewa",
    "Katni (Murwara)",
    "Singrauli",
    "Burhanpur",
    "Khandwa",
    "Bhind",
    "Morena",
    "Chhindwara",
    "Guna",
    "Shivpuri",
    "Vidisha"
  ],
  "Maharashtra": [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Thane",
    "Pimpri-Chinchwad",
    "Nashik",
    "Kalyan-Dombivli",
    "Vasai-Virar",
    "Aurangabad (Chhatrapati Sambhajinagar)",
    "Navi Mumbai",
    "Solapur",
    "Mira-Bhayandar",
    "Kolhapur",
    "Amravati",
    "Nanded",
    "Sangli",
    "Jalgaon",
    "Akola",
    "Latur",
    "Dhule",
    "Ahmednagar",
    "Chandrapur",
    "Parbhani",
    "Ichalkaranji",
    "Jalna",
    "Bhusawal",
    "Panvel",
    "Satara"
  ],
  "Manipur": [
    "Imphal",
    "Churachandpur",
    "Thoubal",
    "Ukhrul",
    "Senapati",
    "Kakching"
  ],
  "Meghalaya": [
    "Shillong",
    "Tura",
    "Jowai",
    "Nongpoh",
    "Williamnagar",
    "Cherrapunji"
  ],
  "Mizoram": [
    "Aizawl",
    "Lunglei",
    "Saiha",
    "Champhai",
    "Kolasib"
  ],
  "Nagaland": [
    "Kohima",
    "Dimapur",
    "Mokokchung",
    "Tuensang",
    "Wokha"
  ],
  "Odisha": [
    "Bhubaneswar",
    "Cuttack",
    "Rourkela",
    "Berhampur",
    "Sambalpur",
    "Puri",
    "Balasore",
    "Bhadrak",
    "Baripada",
    "Jharsuguda",
    "Bargarh",
    "Jeypore"
  ],
  "Punjab": [
    "Ludhiana",
    "Amritsar",
    "Jalandhar",
    "Patiala",
    "Bathinda",
    "Mohali (SAS Nagar)",
    "Pathankot",
    "Hoshiarpur",
    "Batala",
    "Moga",
    "Abohar",
    "Khanna",
    "Phagwara",
    "Firozpur",
    "Rajpura",
    "Muktsar"
  ],
  "Rajasthan": [
    "Jaipur",
    "Jodhpur",
    "Kota",
    "Bikaner",
    "Ajmer",
    "Udaipur",
    "Bhilwara",
    "Alwar",
    "Sikar",
    "Sri Ganganagar",
    "Bharatpur",
    "Hanumangarh",
    "Tonk",
    "Pali",
    "Baran",
    "Beawar",
    "Churu",
    "Jhunjhunu"
  ],
  "Sikkim": [
    "Gangtok",
    "Namchi",
    "Geyzing",
    "Mangan"
  ],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli (Trichy)",
    "Salem",
    "Tiruppur",
    "Erode",
    "Vellore",
    "Thoothukudi (Tuticorin)",
    "Tirunelveli",
    "Nagercoil",
    "Thanjavur",
    "Dindigul",
    "Kanchipuram",
    "Karaikudi",
    "Kumbakonam",
    "Cuddalore",
    "Neyveli",
    "Hosur"
  ],
  "Telangana": [
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Karimnagar",
    "Ramagundam",
    "Khammam",
    "Mahbubnagar",
    "Nalgonda",
    "Adilabad",
    "Suryapet",
    "Miryalaguda",
    "Siddipet"
  ],
  "Tripura": [
    "Agartala",
    "Dharmanagar",
    "Udaipur",
    "Kailasahar",
    "Belonia"
  ],
  "Uttar Pradesh": [
    "Lucknow",
    "Kanpur",
    "Ghaziabad",
    "Agra",
    "Meerut",
    "Varanasi",
    "Prayagraj (Allahabad)",
    "Bareilly",
    "Aligarh",
    "Moradabad",
    "Saharanpur",
    "Gorakhpur",
    "Noida",
    "Greater Noida",
    "Firozabad",
    "Jhansi",
    "Muzaffarnagar",
    "Mathura",
    "Ayodhya",
    "Rampur",
    "Shahjahanpur",
    "Hapur",
    "Lakhimpur",
    "Gonda",
    "Basti",
    "Amroha"
  ],
  "Uttarakhand": [
    "Dehradun",
    "Haridwar",
    "Haldwani",
    "Roorkee",
    "Kashipur",
    "Rudrapur",
    "Rishikesh",
    "Pithoragarh"
  ],
  "West Bengal": [
    "Kolkata",
    "Howrah",
    "Siliguri",
    "Asansol",
    "Durgapur",
    "Bardhaman",
    "Malda",
    "Baharampur",
    "Kharagpur",
    "Haldia",
    "Jalpaiguri",
    "Balurghat",
    "Darjeeling",
    "Shantiniketan",
    "Habra",
    "Barasat",
    "Kharagpur"
  ],
  "Andaman and Nicobar Islands": [
    "Port Blair"
  ],
  "Chandigarh": [
    "Chandigarh"
  ],
  "Dadra and Nagar Haveli and Daman and Diu": [
    "Silvassa",
    "Daman",
    "Diu"
  ],
  "Delhi": [
    "Delhi",
    "New Delhi",
    "Central Delhi",
    "East Delhi",
    "West Delhi",
    "North Delhi",
    "South Delhi",
    "Dwarka",
    "Rohini",
    "Vasant Kunj"
  ],
  "Jammu and Kashmir": [
    "Srinagar",
    "Jammu",
    "Anantnag",
    "Baramulla",
    "Kathua",
    "Sopore",
    "Samba",
    "Udhampur",
    "Poonch"
  ],
  "Ladakh": [
    "Leh",
    "Kargil"
  ],
  "Lakshadweep": [
    "Kavaratti",
    "Minicoy",
    "Amini"
  ],
  "Puducherry": [
    "Puducherry",
    "Karaikal",
    "Mahe",
    "Yanam"
  ]
};

export const INDIA_STATES = Object.keys(INDIA_STATES_AND_CITIES).sort();
