// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Helper function to create a fully chainable, thenable mock Supabase query builder
function createMockQueryChain(defaultValue: any = [], defaultError: any = null) {
  const chain: any = {
    then: (onfulfilled?: any, onrejected?: any) => {
      return Promise.resolve({ data: defaultValue, error: defaultError }).then(onfulfilled, onrejected);
    },
    catch: (onrejected?: any) => {
      return Promise.resolve({ data: defaultValue, error: defaultError }).catch(onrejected);
    },
    finally: (onfinally?: any) => {
      return Promise.resolve({ data: defaultValue, error: defaultError }).finally(onfinally);
    }
  };

  const methods = [
    'select', 'insert', 'update', 'delete', 'upsert',
    'eq', 'neq', 'gt', 'gte', 'lt', 'lte', 'like', 'ilike',
    'is', 'in', 'contains', 'containedBy', 'rangeGt', 'rangeGte',
    'rangeLt', 'rangeLte', 'rangeAdjacent', 'overlaps',
    'textSearch', 'match', 'not', 'or', 'filter',
    'order', 'limit', 'range', 'single', 'maybeSingle',
    'csv', 'geojson', 'explain', 'rollback'
  ];

  methods.forEach(method => {
    chain[method] = (...args: any[]) => {
      if (method === 'single' || method === 'maybeSingle') {
        return createMockQueryChain(null, defaultError);
      }
      return chain;
    };
  });

  return chain;
}

const VITE_SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const VITE_SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!VITE_SUPABASE_URL) console.warn("VITE_SUPABASE_URL is missing!");
if (!VITE_SUPABASE_PUBLISHABLE_KEY) console.warn("VITE_SUPABASE_PUBLISHABLE_KEY is missing!");

let supabaseInstance;
try {
  const rawUrl = VITE_SUPABASE_URL || "https://lnxzkusbhidaqhhsxjtk.supabase.co";
  const rawKey = VITE_SUPABASE_PUBLISHABLE_KEY || "sb_publishable_3RZcGzoDXliNivNsbgGHjw_1rmQgGFf";
  
  // Robust URL Cleaning: 
  // 1. Trim whitespace
  // 2. Parse as URL to extract just the origin if it's a full URL with paths
  let url = rawUrl.trim();
  try {
    const urlObj = new URL(url);
    url = urlObj.origin;
  } catch (e) {
    // If it's not a valid URL start, just try basic cleaning
    url = url.replace(/\/$/, "");
  }
  
  const key = rawKey.trim();
  
  if (!url || !key) {
    console.warn("Supabase credentials missing from environment. Using mock client to prevent 'Failed to fetch' errors.");
    
    // Return a mock instance that doesn't make network requests
    supabaseInstance = { 
      auth: { 
        onAuthStateChange: (callback: any) => {
          // Immediately trigger with null session to allow app to proceed
          setTimeout(() => callback('INITIAL_SESSION', null), 0);
          return { data: { subscription: { unsubscribe: () => {} } } }; 
        }, 
        getSession: async () => ({ data: { session: null }, error: null }),
        getUser: async () => ({ data: { user: null }, error: null }),
        signInWithPassword: async () => ({ data: { session: null, user: null }, error: new Error("Mock mode") }),
        signUp: async () => ({ data: { session: null, user: null }, error: new Error("Mock mode") }),
        signOut: async () => ({ error: null })
      },
      storage: {
        from: () => ({
          upload: async () => ({ data: null, error: new Error("Mock mode") }),
          getPublicUrl: () => ({ data: { publicUrl: "" } })
        })
      },
      from: () => createMockQueryChain([], null),
      rpc: async () => ({ data: null, error: null })
    } as any;
  } else {
    supabaseInstance = createClient<Database>(url, key, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
      global: {
        headers: { 'x-application-name': 'sruvo-web' },
        fetch: async (...args) => {
          try {
            return await fetch(...args);
          } catch (err) {
            if (err instanceof Error && err.message === 'Failed to fetch') {
              console.error("CRITICAL: Network request failed (Failed to fetch).", {
                url: args[0],
                supabaseUrl: url,
                isSupabaseRequest: String(args[0]).includes(url)
              });
            }
            throw err;
          }
        }
      }
    });
  }
} catch (err: unknown) {
  const error = err instanceof Error ? err : new Error(String(err));
  console.error("Critical: Failed to initialize Supabase client:", error);
  
  const fallbackError = new Error(`Supabase initialization failed: ${error.message}`);
  
  supabaseInstance = { 
    auth: { 
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }), 
      getSession: async () => ({ data: { session: null }, error: null }),
      getUser: async () => ({ data: { user: null }, error: null }),
      signInWithPassword: async () => ({ data: { session: null, user: null }, error: fallbackError }),
      signUp: async () => ({ data: { session: null, user: null }, error: fallbackError }),
      signOut: async () => ({ error: null })
    },
    from: () => createMockQueryChain([], fallbackError)
  } as any;
}

export const supabase = supabaseInstance;