// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const VITE_SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const VITE_SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!VITE_SUPABASE_URL) console.warn("VITE_SUPABASE_URL is missing!");
if (!VITE_SUPABASE_PUBLISHABLE_KEY) console.warn("VITE_SUPABASE_PUBLISHABLE_KEY is missing!");

let supabaseInstance;
try {
  const rawUrl = VITE_SUPABASE_URL || "https://kvynslxotglracfgacgn.supabase.co";
  const rawKey = VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2eW5zbHhvdGdscmFjZmdhY2duIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ1NDMwNjUsImV4cCI6MjA4MDExOTA2NX0.i9-bXgL2891ji3AK-mS4wLp6HDl4DIStrcJeONNEKP0";
  
  // Robust URL Cleaning: 
  // 1. Trim whitespace
  // 2. Parse as URL to extract just the origin if it's a full URL with paths
  let url = rawUrl.trim();
  try {
    const urlObj = new URL(url);
    url = urlObj.origin;
  } catch (e) {
    // If it's not a valid URL start, just try basic cleaning
    url = url.replace(/\/$/, "");
  }
  
  const key = rawKey.trim();
  
  if (!VITE_SUPABASE_URL || !VITE_SUPABASE_PUBLISHABLE_KEY) {
    console.warn("Supabase credentials missing from environment. Using mock client to prevent 'Failed to fetch' errors.");
    
    // Return a mock instance that doesn't make network requests
    supabaseInstance = { 
      auth: { 
        onAuthStateChange: (callback: any) => {
          // Immediately trigger with null session to allow app to proceed
          setTimeout(() => callback('INITIAL_SESSION', null), 0);
          return { data: { subscription: { unsubscribe: () => {} } } }; 
        }, 
        getSession: async () => ({ data: { session: null }, error: null }),
        getUser: async () => ({ data: { user: null }, error: null }),
        signInWithPassword: async () => ({ data: { session: null, user: null }, error: new Error("Mock mode") }),
        signUp: async () => ({ data: { session: null, user: null }, error: new Error("Mock mode") }),
        signOut: async () => ({ error: null })
      },
      storage: {
        from: () => ({
          upload: async () => ({ data: null, error: new Error("Mock mode") }),
          getPublicUrl: () => ({ data: { publicUrl: "" } })
        })
      },
      from: () => ({
        select: () => ({
          eq: () => ({
            single: async () => ({ data: null, error: null }),
            maybeSingle: async () => ({ data: null, error: null }),
            order: () => ({
              limit: async () => ({ data: [], error: null })
            })
          }),
          order: () => ({
            limit: async () => ({ data: [], error: null })
          }),
          limit: async () => ({ data: [], error: null })
        }),
        insert: async () => ({ data: null, error: null }),
        update: async () => ({ data: null, error: null }),
        delete: async () => ({ data: null, error: null }),
        upsert: async () => ({ data: null, error: null })
      }),
      rpc: async () => ({ data: null, error: null })
    } as any;
  } else {
    supabaseInstance = createClient<Database>(url, key, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
      global: {
        headers: { 'x-application-name': 'sruvo-web' },
        fetch: async (...args) => {
          try {
            return await fetch(...args);
          } catch (err) {
            if (err instanceof Error && err.message === 'Failed to fetch') {
              console.error("CRITICAL: Network request failed (Failed to fetch).", {
                url: args[0],
                supabaseUrl: url,
                isSupabaseRequest: String(args[0]).includes(url)
              });
            }
            throw err;
          }
        }
      }
    });
  }
} catch (err: unknown) {
  const error = err instanceof Error ? err : new Error(String(err));
  console.error("Critical: Failed to initialize Supabase client:", error);
  
  const fallbackError = new Error(`Supabase initialization failed: ${error.message}`);
  
  supabaseInstance = { 
    auth: { 
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }), 
      getSession: async () => ({ data: { session: null }, error: null }),
      getUser: async () => ({ data: { user: null }, error: null }),
      signInWithPassword: async () => ({ data: { session: null, user: null }, error: fallbackError }),
      signUp: async () => ({ data: { session: null, user: null }, error: fallbackError }),
      signOut: async () => ({ error: null })
    },
    from: () => ({
      select: () => ({
        eq: () => ({
          single: async () => ({ data: null, error: fallbackError }),
          maybeSingle: async () => ({ data: null, error: fallbackError }),
          order: () => ({
            limit: async () => ({ data: [], error: fallbackError })
          })
        }),
        order: () => ({
          limit: async () => ({ data: [], error: fallbackError })
        }),
        limit: async () => ({ data: [], error: fallbackError })
      }),
      insert: async () => ({ data: null, error: fallbackError }),
      update: async () => ({ data: null, error: fallbackError }),
      delete: async () => ({ data: null, error: fallbackError }),
      upsert: async () => ({ data: null, error: fallbackError })
    })
  } as any;
}

export const supabase = supabaseInstance;